/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "userrecords-dev",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:b91a7374-3c6e-4f90-aa26-47b332bc3ecb",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_XSxVZ3zwJ",
    "aws_user_pools_web_client_id": "7bsot9ssj3e0cpbpbi46osio7l",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "rpsuserapi",
            "endpoint": "https://0aam7b7qwa.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
